services:
  training:
    build:
      context: .
      network: host
    container_name: bubbling-detection-training
    volumes:
      - .:/app
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    privileged: true
    shm_size: '8gb'
    environment:
      - HIP_VISIBLE_DEVICES=0
      - HSA_OVERRIDE_GFX_VERSION=11.0.0 # Navi 31 (7900 XTX/XT)
    command: >
      bash -lc "set -euo pipefail;
      chmod +x ./retrain.sh ./evaluate.sh;
      ./retrain.sh;
      ./evaluate.sh"

  pipeline:
    build:
      context: .
      network: host
    container_name: bubbling-detection-pipeline
    volumes:
      - .:/app
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    privileged: true
    shm_size: '8gb'
    environment:
      - HIP_VISIBLE_DEVICES=0
      - HSA_OVERRIDE_GFX_VERSION=11.0.0 # Navi 31 (7900 XTX/XT)
    command: >
      bash -lc "set -euo pipefail;
      chmod +x ./run_pipeline.sh;
      ./run_pipeline.sh"

  cleanup:
    build:
      context: .
      network: host
    container_name: bubbling-detection-training
    volumes:
      - .:/app
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    privileged: true
    shm_size: '8gb'
    environment:
      - HIP_VISIBLE_DEVICES=0
      - HSA_OVERRIDE_GFX_VERSION=11.0.0 # Navi 31 (7900 XTX/XT)
    command: >
      bash -lc "set -euo pipefail;
      chmod +x ./cleanup.sh;
      ./cleanup.sh;
